# Generated by Django 3.2.9 on 2021-12-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('name_cn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_cn', models.CharField(blank=True, max_length=50, null=True)),
                ('countryid', models.ForeignKey(db_column='countryid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Search.country')),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('familyname', models.CharField(blank=True, max_length=20, null=True)),
                ('shortname', models.CharField(blank=True, max_length=20, null=True)),
                ('firstname_cn', models.CharField(blank=True, max_length=20, null=True)),
                ('familyname_cn', models.CharField(blank=True, max_length=20, null=True)),
                ('shortname_cn', models.CharField(blank=True, max_length=10, null=True)),
                ('originname', models.CharField(blank=True, max_length=40, null=True)),
                ('yearofbirth', models.IntegerField(blank=True, null=True)),
                ('countryid', models.ForeignKey(db_column='countryid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Search.country')),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname_en', models.CharField(blank=True, max_length=50, null=True)),
                ('shortname_en', models.CharField(blank=True, max_length=10, null=True)),
                ('fullname_cn', models.CharField(blank=True, max_length=30, null=True)),
                ('shortname_cn', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Club'), (1, 'National')], default=0)),
                ('countryid', models.ForeignKey(db_column='countryid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Search.country')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Teamtoleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_start', models.DateField(blank=True, null=True)),
                ('season_end', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.team')),
            ],
            options={
                'db_table': 'teamtoleague',
                'unique_together': {('team', 'league', 'season_start')},
            },
        ),
        migrations.CreateModel(
            name='Playertoteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('pos', models.CharField(blank=True, max_length=5, null=True)),
                ('time_join', models.DateField(blank=True, null=True)),
                ('time_leave', models.DateField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Local'), (1, 'Born')], default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.team')),
            ],
            options={
                'db_table': 'playertoteam',
                'unique_together': {('player', 'team', 'time_join')},
            },
        ),
    ]
